version: '3.8'

services:
  # 1. 关系型数据库 (PostgreSQL)
  postgres:
    image: postgres:15-alpine
    container_name: minqq_pg
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: LetsChat
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - im_net

  # 2. 缓存数据库 (Redis)
  redis:
    image: redis:7-alpine
    container_name: LetsChat_redis
    command: redis-server --requirepass "redis_pwd_123"
    ports:
      - "6379:6379"
    networks:
      - im_net

  # 3. 对象存储 (MinIO - 类似 S3)
  minio:
    image: minio/minio
    container_name: minqq_minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio_admin
      MINIO_ROOT_PASSWORD: minio_password
    ports:
      - "9000:9000" # API 端口
      - "9001:9001" # 控制台端口
    volumes:
      - minio_data:/data
    networks:
      - im_net

networks:
  im_net:
    driver: bridge

volumes:
  pg_data:
  minio_data: