version: '3.8'

services:
  # 1. 关系型数据库 (PostgreSQL)
  postgres:
    image: postgres:15-alpine
    container_name: minqq_pg
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: LetsChat
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - im_net

  # 2. 缓存数据库 (Redis)
  redis:
    image: redis:7-alpine
    container_name: LetsChat_redis
    command: redis-server --requirepass "redis_pwd_123"
    ports:
      - "6379:6379"
    networks:
      - im_net

  # 3. 对象存储 (SeaweedFS)
  weed_master:
    image: chrislusf/seaweedfs:3.74
    container_name: letschat_weed_master
    command: "master -ip=weed_master -mdir=/data"
    ports:
      - "9333:9333"
    volumes:
      - weed_master_data:/data
    networks:
      - im_net

  weed_volume:
    image: chrislusf/seaweedfs:3.74
    container_name: letschat_weed_volume
    command: "volume -mserver=weed_master:9333 -ip=weed_volume -port=8080 -dir=/data"
    depends_on:
      - weed_master
    ports:
      - "8080:8080"
    volumes:
      - weed_volume_data:/data
    networks:
      - im_net

networks:
  im_net:
    driver: bridge

volumes:
  pg_data:
  weed_master_data:
  weed_volume_data:
